export const STATES = [
    'AC',
    'AL',
    'AP',
    'AM',
    'BA',
    'CE',
    'DF',
    'ES',
    'GO',
    'MA',
    'MT',
    'MS',
    'MG',
    'PA',
    'PB',
    'PR',
    'PE',
    'PI',
    'RJ',
    'RN',
    'RS',
    'RO',
    'RR',
    'SC',
    'SP',
    'SE',
    'TO',
];

export const STATES_TO_NAME: Record<string, any> = {
    SP: 'São Paulo',
    RJ: 'Rio de Janeiro',
    ES: 'Espírito Santo',
    GO: 'Goiás',
    MG: 'Minas Gerais',
    CE: 'Ceará',
    BA: 'Bahia',
    DF: 'Distrito Federal',
    MT: 'Mato Grosso',
    MS: 'Mato Grosso do Sul',
    RS: 'Rio Grande do Sul',
    PA: 'Pará',
    PB: 'Paraíba',
    MA: 'Maranhão',
    PR: 'Paraná',
    PE: 'Pernambuco',
    PI: 'Piauí',
    RN: 'Rio Grande do Norte',
    RO: 'Rondônia',
    RR: 'Roraima',
    SC: 'Santa Catarina',
    AC: 'Acre',
    AL: 'Alagoas',
    AP: 'Amapá',
    AM: 'Amazonas',
    SE: 'Sergipe',
    TO: 'Tocantins',
};

export const stateCodeToName = (acronym: string) =>
    STATES_TO_NAME[acronym.toUpperCase()];
