name: Lint Code Base

on: push

jobs:
    check-eslint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
            # - run: npm install
            - run: npm install -g prettier
            - run: npx prettier --check src/
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
